### ISSUE TITLE
META: Address fixable problems found with the existing Bower import

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#216]
The current Bower import code, runnable with:

```console
GITHUB_TOKEN=<token> spago run -m Registry.Scripts.BowerImport
```

...produces a `bower-exclusions.json` file with all packages that don't produce valid manifests. Many of these packages _could_ produce valid manifests with a little tweaking. For example, some packages have a trivial misspelling of their LICENSE type, which we can rewrite for them:

https://github.com/purescript/registry/blob/3f5c48e518f657ab03c4178df976648c9fb1437f/ci/src/Registry/Scripts/BowerImport.purs#L226-L232

This issue tracks classifying errors that are currently excluding packages, but which we would like to fix so that more packages are included in the registry.

- [x] https://github.com/purescript/registry/issues/211
- [x] https://github.com/purescript/registry/issues/217
- [x] https://github.com/purescript/registry/issues/218
- [x] https://github.com/purescript/registry/issues/219
- [x] https://github.com/purescript/registry/issues/220
- [x] https://github.com/purescript/registry/issues/222
- [x] https://github.com/purescript/registry/issues/226
- [x] https://github.com/purescript/registry/issues/233
- [x] https://github.com/purescript/registry/issues/249

**Comment by thomashoneyman** [comment]
@f-f By far the most failures come from `MissingLicense` errors, and so #220 would be the most impactful of all of these issues. However, it's also potentially the most difficult -- we really would have to find a tool that provides this functionality already.

**Comment by f-f** [comment]
@thomashoneyman do you happen to have numbers at hand about the amount of failures affected by different issues?

**Comment by thomashoneyman** [comment]
I don't! But I think we _should_:
- https://github.com/purescript/registry/issues/222

**Comment by f-f** [comment]
It looks like this is now done! Thanks everyone :heart:
